group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.25
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.5
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.75
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 1
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.25
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.5
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.75
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 1
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.25
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.5
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.75
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 1
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.25
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.5
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.75
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 1
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.25
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.5
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 0.75
python main.py --force_out_dim 10 --no_class_remap --group_id rotated-mnist.ablation_size.$group_tag --dataset MNIST --n_rotate 15 --rotate_step 5 --run_name rotated-mnist.ablation_size.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --ogd --subset_size 1