group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 0 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.25 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 0 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.5 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 0 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.75 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 0 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 1 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 1 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.25 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 1 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.5 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 1 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.75 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 1 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 1 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 2 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.25 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 2 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.5 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 2 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.75 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 2 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 1 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 3 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.25 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 3 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.5 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 3 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.75 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 3 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 1 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 4 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.25 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 4 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.5 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 4 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 0.75 --ogd
python main.py --n_permutation 15 --no_class_remap --memory_size 100 --group_id permuted-mnist.ablation_size.$group_tag --dataset MNIST --run_name permuted-mnist.ablation_size.$group_tag --force_out_dim 10 --run_seed 4 --lr 0.001 --batch_size 32 --hidden_dim 100 --nepoch 5 --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --subset_size 1 --ogd