group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 1e-05  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.01  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 64 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 1 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 20 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 
python main.py --memory_size 100 --group_id gs_split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name gs_split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 256 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.1  --batch_size 256 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val  --reg_coef 0.0 --wandb_dryrun 