group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.sgd.$group_tag --group_id permuted-mnist.sgd.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5  --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.sgd.$group_tag --group_id permuted-mnist.sgd.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5  --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.sgd.$group_tag --group_id permuted-mnist.sgd.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5  --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.sgd.$group_tag --group_id permuted-mnist.sgd.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5  --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.sgd.$group_tag --group_id permuted-mnist.sgd.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5  --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd.$group_tag --group_id permuted-mnist.ogd.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd.$group_tag --group_id permuted-mnist.ogd.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd.$group_tag --group_id permuted-mnist.ogd.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd.$group_tag --group_id permuted-mnist.ogd.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd.$group_tag --group_id permuted-mnist.ogd.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd-plus.$group_tag --group_id permuted-mnist.ogd-plus.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd-plus.$group_tag --group_id permuted-mnist.ogd-plus.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd-plus.$group_tag --group_id permuted-mnist.ogd-plus.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd-plus.$group_tag --group_id permuted-mnist.ogd-plus.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ogd-plus.$group_tag --group_id permuted-mnist.ogd-plus.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun --reg_coef 0.0


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ewc.$group_tag --group_id permuted-mnist.ewc.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name EWC --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ewc.$group_tag --group_id permuted-mnist.ewc.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name EWC --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ewc.$group_tag --group_id permuted-mnist.ewc.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name EWC --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ewc.$group_tag --group_id permuted-mnist.ewc.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name EWC --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.ewc.$group_tag --group_id permuted-mnist.ewc.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name EWC --agent_type regularization --no_val --wandb_dryrun --reg_coef 1


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.si.$group_tag --group_id permuted-mnist.si.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name SI --agent_type regularization --no_val --wandb_dryrun --reg_coef 10
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.si.$group_tag --group_id permuted-mnist.si.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name SI --agent_type regularization --no_val --wandb_dryrun --reg_coef 10
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.si.$group_tag --group_id permuted-mnist.si.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name SI --agent_type regularization --no_val --wandb_dryrun --reg_coef 10
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.si.$group_tag --group_id permuted-mnist.si.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name SI --agent_type regularization --no_val --wandb_dryrun --reg_coef 10
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.si.$group_tag --group_id permuted-mnist.si.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name SI --agent_type regularization --no_val --wandb_dryrun --reg_coef 10


python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.mas.$group_tag --group_id permuted-mnist.mas.$group_tag --run_seed 0 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name MAS --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.mas.$group_tag --group_id permuted-mnist.mas.$group_tag --run_seed 1 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name MAS --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.mas.$group_tag --group_id permuted-mnist.mas.$group_tag --run_seed 2 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name MAS --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.mas.$group_tag --group_id permuted-mnist.mas.$group_tag --run_seed 3 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name MAS --agent_type regularization --no_val --wandb_dryrun --reg_coef 1
python main.py --n_permutation 15 --force_out_dim 10 --no_class_remap  --dataset MNIST --run_name permuted-mnist.mas.$group_tag --group_id permuted-mnist.mas.$group_tag --run_seed 4 --memory_size 100 --lr 0.001 --batch_size 32 --val_check_interval 10000000 --hidden_dim 100 --nepoch 5   --agent_name MAS --agent_type regularization --no_val --wandb_dryrun --reg_coef 1

