group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --memory_size 100 --group_id split-cub.sgd.$group_tag --run_name split-cub.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 0  --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.sgd.$group_tag --run_name split-cub.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 1  --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.sgd.$group_tag --run_name split-cub.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 2  --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.sgd.$group_tag --run_name split-cub.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 3  --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.sgd.$group_tag --run_name split-cub.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 4  --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun


python main.py --memory_size 100 --group_id split-cub.ogd.$group_tag --run_name split-cub.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 0 --ogd --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd.$group_tag --run_name split-cub.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 1 --ogd --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd.$group_tag --run_name split-cub.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 2 --ogd --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd.$group_tag --run_name split-cub.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 3 --ogd --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd.$group_tag --run_name split-cub.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 4 --ogd --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun


python main.py --memory_size 100 --group_id split-cub.ogd-plus.$group_tag --run_name split-cub.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 0 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd-plus.$group_tag --run_name split-cub.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 1 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd-plus.$group_tag --run_name split-cub.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 2 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd-plus.$group_tag --run_name split-cub.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 3 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ogd-plus.$group_tag --run_name split-cub.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 0.0 --batch_size 10 --run_seed 4 --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --is_split_cub --wandb_dryrun


python main.py --memory_size 100 --group_id split-cub.ewc.$group_tag --run_name split-cub.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1000 --batch_size 10 --run_seed 0   --agent_name EWC --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ewc.$group_tag --run_name split-cub.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1000 --batch_size 10 --run_seed 1   --agent_name EWC --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ewc.$group_tag --run_name split-cub.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1000 --batch_size 10 --run_seed 2   --agent_name EWC --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ewc.$group_tag --run_name split-cub.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1000 --batch_size 10 --run_seed 3   --agent_name EWC --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.ewc.$group_tag --run_name split-cub.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1000 --batch_size 10 --run_seed 4   --agent_name EWC --agent_type regularization --no_val --is_split_cub --wandb_dryrun


python main.py --memory_size 100 --group_id split-cub.si.$group_tag --run_name split-cub.si.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 10 --batch_size 10 --run_seed 0   --agent_name SI --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.si.$group_tag --run_name split-cub.si.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 10 --batch_size 10 --run_seed 1   --agent_name SI --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.si.$group_tag --run_name split-cub.si.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 10 --batch_size 10 --run_seed 2   --agent_name SI --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.si.$group_tag --run_name split-cub.si.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 10 --batch_size 10 --run_seed 3   --agent_name SI --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.si.$group_tag --run_name split-cub.si.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 10 --batch_size 10 --run_seed 4   --agent_name SI --agent_type regularization --no_val --is_split_cub --wandb_dryrun


python main.py --memory_size 100 --group_id split-cub.mas.$group_tag --run_name split-cub.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1 --batch_size 10 --run_seed 0   --agent_name MAS --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.mas.$group_tag --run_name split-cub.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1 --batch_size 10 --run_seed 1   --agent_name MAS --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.mas.$group_tag --run_name split-cub.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1 --batch_size 10 --run_seed 2   --agent_name MAS --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.mas.$group_tag --run_name split-cub.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1 --batch_size 10 --run_seed 3   --agent_name MAS --agent_type regularization --no_val --is_split_cub --wandb_dryrun
python main.py --memory_size 100 --group_id split-cub.mas.$group_tag --run_name split-cub.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 20 --other_split_size 20 --hidden_dim 256 --model_type alexnet  --nepoch 75 --model_name AlexNetCL --lr 0.001  --reg_coef 1 --batch_size 10 --run_seed 4   --agent_name MAS --agent_type regularization --no_val --is_split_cub --wandb_dryrun

