group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --memory_size 100 --group_id split-mnist.sgd.$group_tag  --dataset MNIST --run_name split-mnist.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000  --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.sgd.$group_tag  --dataset MNIST --run_name split-mnist.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000  --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.sgd.$group_tag  --dataset MNIST --run_name split-mnist.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000  --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.sgd.$group_tag  --dataset MNIST --run_name split-mnist.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000  --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.sgd.$group_tag  --dataset MNIST --run_name split-mnist.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000  --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0


python main.py --memory_size 100 --group_id split-mnist.ogd.$group_tag  --dataset MNIST --run_name split-mnist.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000 --ogd --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd.$group_tag  --dataset MNIST --run_name split-mnist.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000 --ogd --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd.$group_tag  --dataset MNIST --run_name split-mnist.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000 --ogd --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd.$group_tag  --dataset MNIST --run_name split-mnist.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000 --ogd --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd.$group_tag  --dataset MNIST --run_name split-mnist.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000 --ogd --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0


python main.py --memory_size 100 --group_id split-mnist.ogd-plus.$group_tag  --dataset MNIST --run_name split-mnist.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000 --ogd_plus --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd-plus.$group_tag  --dataset MNIST --run_name split-mnist.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000 --ogd_plus --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd-plus.$group_tag  --dataset MNIST --run_name split-mnist.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000 --ogd_plus --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd-plus.$group_tag  --dataset MNIST --run_name split-mnist.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000 --ogd_plus --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0
python main.py --memory_size 100 --group_id split-mnist.ogd-plus.$group_tag  --dataset MNIST --run_name split-mnist.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000 --ogd_plus --agent_name OGD --agent_type ogd_plus  --no_val --wandb_dryrun   --reg_coef 0.0


python main.py --memory_size 100 --group_id split-mnist.ewc.$group_tag  --dataset MNIST --run_name split-mnist.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000   --agent_name EWC --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 1000
python main.py --memory_size 100 --group_id split-mnist.ewc.$group_tag  --dataset MNIST --run_name split-mnist.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000   --agent_name EWC --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 1000
python main.py --memory_size 100 --group_id split-mnist.ewc.$group_tag  --dataset MNIST --run_name split-mnist.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000   --agent_name EWC --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 1000
python main.py --memory_size 100 --group_id split-mnist.ewc.$group_tag  --dataset MNIST --run_name split-mnist.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000   --agent_name EWC --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 1000
python main.py --memory_size 100 --group_id split-mnist.ewc.$group_tag  --dataset MNIST --run_name split-mnist.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000   --agent_name EWC --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 1000


python main.py --memory_size 100 --group_id split-mnist.si.$group_tag  --dataset MNIST --run_name split-mnist.si.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000   --agent_name SI --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10000
python main.py --memory_size 100 --group_id split-mnist.si.$group_tag  --dataset MNIST --run_name split-mnist.si.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000   --agent_name SI --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10000
python main.py --memory_size 100 --group_id split-mnist.si.$group_tag  --dataset MNIST --run_name split-mnist.si.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000   --agent_name SI --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10000
python main.py --memory_size 100 --group_id split-mnist.si.$group_tag  --dataset MNIST --run_name split-mnist.si.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000   --agent_name SI --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10000
python main.py --memory_size 100 --group_id split-mnist.si.$group_tag  --dataset MNIST --run_name split-mnist.si.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000   --agent_name SI --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10000


python main.py --memory_size 100 --group_id split-mnist.mas.$group_tag  --dataset MNIST --run_name split-mnist.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 0 --hidden_dim 100 --val_check_interval 10000000   --agent_name MAS --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10
python main.py --memory_size 100 --group_id split-mnist.mas.$group_tag  --dataset MNIST --run_name split-mnist.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 1 --hidden_dim 100 --val_check_interval 10000000   --agent_name MAS --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10
python main.py --memory_size 100 --group_id split-mnist.mas.$group_tag  --dataset MNIST --run_name split-mnist.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 2 --hidden_dim 100 --val_check_interval 10000000   --agent_name MAS --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10
python main.py --memory_size 100 --group_id split-mnist.mas.$group_tag  --dataset MNIST --run_name split-mnist.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 3 --hidden_dim 100 --val_check_interval 10000000   --agent_name MAS --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10
python main.py --memory_size 100 --group_id split-mnist.mas.$group_tag  --dataset MNIST --run_name split-mnist.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 2 --other_split_size 2 --rand_split  --nepoch 5 --batch_size 32 --run_seed 4 --hidden_dim 100 --val_check_interval 10000000   --agent_name MAS --agent_type regularization  --no_val --wandb_dryrun   --reg_coef 10

