group_tag=$(date +'%Y-%m-%d-%H-%M')


python main.py --memory_size 100 --group_id split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0   --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1   --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2   --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3   --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.sgd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.sgd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4   --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0


python main.py --memory_size 100 --group_id split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1  --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2  --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3  --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4  --ogd --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0


python main.py --memory_size 100 --group_id split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0
python main.py --memory_size 100 --group_id split-cifar100.ogd-plus.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ogd-plus.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4  --ogd_plus --agent_name OGD --agent_type ogd_plus --no_val --wandb_dryrun  --reg_coef 0.0


python main.py --memory_size 100 --group_id split-cifar100.ewc.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0    --agent_name EWC --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.ewc.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1    --agent_name EWC --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.ewc.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2    --agent_name EWC --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.ewc.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3    --agent_name EWC --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.ewc.$group_tag  --dataset CIFAR100 --run_name split-cifar100.ewc.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4    --agent_name EWC --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10


python main.py --memory_size 100 --group_id split-cifar100.si.$group_tag  --dataset CIFAR100 --run_name split-cifar100.si.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0    --agent_name SI --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.si.$group_tag  --dataset CIFAR100 --run_name split-cifar100.si.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1    --agent_name SI --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.si.$group_tag  --dataset CIFAR100 --run_name split-cifar100.si.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2    --agent_name SI --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.si.$group_tag  --dataset CIFAR100 --run_name split-cifar100.si.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3    --agent_name SI --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.si.$group_tag  --dataset CIFAR100 --run_name split-cifar100.si.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4    --agent_name SI --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10


python main.py --memory_size 100 --group_id split-cifar100.mas.$group_tag  --dataset CIFAR100 --run_name split-cifar100.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 0    --agent_name MAS --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.mas.$group_tag  --dataset CIFAR100 --run_name split-cifar100.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 1    --agent_name MAS --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.mas.$group_tag  --dataset CIFAR100 --run_name split-cifar100.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 2    --agent_name MAS --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.mas.$group_tag  --dataset CIFAR100 --run_name split-cifar100.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 3    --agent_name MAS --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10
python main.py --memory_size 100 --group_id split-cifar100.mas.$group_tag  --dataset CIFAR100 --run_name split-cifar100.mas.$group_tag --is_split --force_out_dim 0 --first_split_size 5 --other_split_size 5 --hidden_dim 100 --nepoch 50 --model_type lenet --model_name LeNetC --lr 0.001  --batch_size 32 --run_seed 4    --agent_name MAS --agent_type regularization --no_val --wandb_dryrun  --reg_coef 10

